services:
  iog-dashboard:
    build: .
    container_name: iog-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      OCTOPUS_API_KEY: ${OCTOPUS_API_KEY}
      OCTOPUS_ACCOUNT_NUMBER: ${OCTOPUS_ACCOUNT_NUMBER}
      OCTOPUS_MPAN: "${OCTOPUS_MPAN}"
      OCTOPUS_METER_SERIAL: ${OCTOPUS_METER_SERIAL}
      OCTOPUS_PRODUCT_CODE: ${OCTOPUS_PRODUCT_CODE}
      OCTOPUS_TARIFF_CODE: ${OCTOPUS_TARIFF_CODE}
